config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  post '/', to: 'sessions#create'

  resources :rewards, only:[:index, :show, :create]
  post '/rewards/:id', to: 'rewards#create'
  
  post '/users/:id', to: 'users#create'

  resources :users, only: [:show]

  resources :admins, only: [:index]

  namespace :admin do
    resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :activities
    resources :rewards
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :users, through: :user_activities
  has_many :user_activities
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :users, through: :user_rewards
  has_many :user_rewards
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :activities, through: :user_activities
  has_many :user_activities

  has_many :rewards, through: :user_rewards
  has_many :user_rewards

  has_secure_password
  enum role: ["default", "admin"]

  def authorize_session
    if admin?
      '/admin/users'
    else
      "/users/#{self.id}"
    end
  end

  def earn_activity_points(activity_id)
    activity_points = Activity.find(activity_id).points
    self.points += activity_points
  end

  def total_points
    activity_points = activities.pluck(:points).inject(:+) || 0
    reward_points = rewards.pluck(:point_cost).inject(:+) || 0
    self.points + activity_points - reward_points
  end

  def claim_reward(reward_id)
    reward_points = Reward.find(reward_id).point_cost
    self.points -= reward_points
  end
end

app/models/user_activity.rb
class UserActivity < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
  validates :user, presence: true
  validates :activity, presence: true 

end

app/models/user_reward.rb
class UserReward < ActiveRecord::Base
  belongs_to :user
  belongs_to :reward

  validates :user, presence: true
  validates :reward, presence: true 

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  # def new
  #   @activity = Activity.new
  # end
  #
  # def create
  #   @activity = Activity.new(activity_params)
  #   if @activity.save
  #     redirect_to admin_index_path
  #   else
  #     flash.now[:error] = "Invalid Activity"
  #     render :new
  #   end
  # end
  #
  # private
  #
  # def activity_params
  #   params.require(:activity).permit(:title, :points)
  # end

end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < Admin::BaseController

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to admin_users_path
    else
      flash.now[:error] = "Invalid Activity"
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update(activity_params)
      redirect_to admin_users_path
    else
      flash.now[:error] = "Invalid Activity"
      render :edit
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.delete

    redirect_to admin_users_path
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :points)
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      flash[:message] = "Reward has been created!"
      redirect_to admin_users_path
    else
      flash.now[:error] = "Invalid Input"
      render :edit
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.delete
    flash[:message] = "Reward has been deleted"
    redirect_to admin_users_path
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(reward_params)
      redirect_to admin_users_path
    else
      flash.now[:error] = "Invalid Input"
      render :edit
    end
  end

  private

  def reward_params
    params.require(:reward).permit(:name, :description, :point_cost)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.where(role: 0)
    @activities = Activity.all
    @rewards = Reward.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
    redirect_to admin_users_path
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      flash.now[:error] = "Invalid Entry"
      render :edit
    end
  end



  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      flash.now[:error] = "Invalid Entry"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @users = User.where(role: 0)
    @activities = Activity.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_admin

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = Reward.all
  end

  def show
    @reward = Reward.find(params[:id])
  end

  def create    
    @reward = Reward.find(params[:id])
    @user = current_user
    user_reward = UserReward.create(reward_id: @reward.id, user_id: @user.id)
    @user.claim_reward(@reward.id)
    redirect_to user_path(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user.authorize_session
    else
      flash[:errors] = "Invalid Login"
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @activities = Activity.all
    @user_activity = UserActivity.new
    @user_activities = @user.activities.all
    @user_rewards = @user.rewards.all
  end

  def create
    @user = User.find(params[:id])
    @activities = Activity.all
    @user_activity = UserActivity.create(user_id: params[:id], activity_id: params[:user_activity][:activity_id])
    @user.earn_activity_points(params[:user_activity][:activity_id])
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end




# @user_activity = current_user.user_activities.find(params[:id])

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/new.html.erb
<%= form_for @activity do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :points %>
  <%= f.text_field :points %>
  <%= f.submit "Create Actitity" %>
<% end %>

app/views/admin/activities/edit.html.erb
<%= form_for [:admin, @activity] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :points %>
  <%= f.text_field :points %>
  <%= f.submit "Update Activity" %>
<% end %>

app/views/admin/activities/new.html.erb
<%= form_for [:admin, @activity] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :points %>
  <%= f.text_field :points %>
  <%= f.submit "Create Activity" %>
<% end %>

app/views/admin/rewards/edit.html.erb
<%= form_for [:admin, @reward] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :point_cost %>
  <%= f.text_field :point_cost %>
  <%= f.submit %>

<% end %>

app/views/admin/rewards/new.html.erb
<%= form_for [:admin, @reward] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :point_cost %>
  <%= f.text_field :point_cost %>
  <%= f.submit %>

<% end %>

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user] do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Update User" %>

<% end %>

app/views/admin/users/index.html.erb
<h1>Welcome Admin</h1>
<%= link_to "Create User", new_admin_user_path %>

<div id="students">
  <ul>
    <% @users.each do |user| %>
      <li><%= user.username %>  <%= link_to "Edit", edit_admin_user_path(user) %>  <%= link_to "Delete", admin_user_path(user), method: :delete %></li>
    <% end %>
  </ul>
</div>

<%= link_to "Create Activity", new_admin_activity_path %>
<div id="activities">
  <ul>
    <% @activities.each do |activity| %>
      <li><%= "#{activity.title} - #{activity.points} points" %>  <%= link_to 'Edit', edit_admin_activity_path(activity)%> <%= link_to "Delete", admin_activity_path(activity), method: :delete %></li>
    <% end %>
  </ul>
</div>

<%= link_to "Create Reward", new_admin_reward_path %>
<div id="rewards">
  <ul>
    <% @rewards.each do |reward| %>
      <li><%= reward.name %> <%= link_to "Edit", edit_admin_reward_path(reward) %> <%= link_to "Delete", admin_reward_path(reward), method: :delete %></li>
    <% end %>
  </ul>
</div>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user] do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommunityPoints</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rewards/index.html.erb
<h1>Rewards</h1>
<div id="rewards">
  <ul>
    <% @rewards.each do |reward| %>
      <li><%= link_to reward.name, reward_path(reward) %></li>
      <li><%= reward.point_cost %></li>
    <% end %>
  </ul>
</div>

app/views/rewards/show.html.erb
<h1><%= @reward.name %></h1>

<%= @reward.description %>
<%= @reward.point_cost %>
<%= @reward.picture %>

<%= link_to "Claim Reward", reward_path(@reward), method: :post %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Update User" %>

<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create" %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %>!</h1>

<%= link_to "Redeem Reward", rewards_path %>

<%= form_for(@user_activity, url: user_path(@user)) do |f| %>
  <div>
    <%= f.collection_select(:activity_id, @activities, :id, :title, prompt: 'Select Activity') %>
    <%= f.submit 'Select activity' %>
  </div>
<% end %>

<% @user_activities.each do |ua| %>
  <ul>
    <li><%= ua.title %> - <%= ua.points %></li>
  </ul>
<% end %>

<% @user_rewards.each do |ur| %>
  <ul>
    <%= ur.name %>
    <%= ur.description %>
    <%= ur.picture %>
  </ul>
<% end %>

<p>
  Total Points - <%= @user.total_points %>
</p>